name: Graveyard
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'graveyard.json'
      - 'graveyard.test.ts'
      - 'package.json'
jobs: 
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm run test
